### ISSUE TITLE
why to check version?

### ISSUE THREAD

**Issue by inekrashevych-callfire** [Ilemon12345/MoneyTransfer#1]
https://github.com/Ilemon12345/MoneyTransfer/blob/2f810f7523d7cf4e99d976788caf8346710699ec/src/main/java/com/yurkov/dao/AccountDao.java#L57

this check would be redundant if we'd substract from balance of the locked entity.

**Comment by Ilemon12345** [comment]
I'm not sure because when two transactions are processing these accounts, the second has to check version because of the first transaction has already updated these accounts and as consequences the first transaction shouldn't be finished because data is changed and we should notity user about it.
